# -*- coding: utf-8 -*-
"""Project Machine Learning with Python: Building Recommender System with Similarity Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gst95xbWw_VJO6mUAT6pXQJNxVyYGlkL
"""

import pandas as pd
import numpy as np

movie_rating_df = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/movie_rating_df.csv')

director_writers = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/directors_writers.csv')
name_df = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/actor_name.csv')

movie_rating_df.head()

director_writers.head()

name_df.head()

print("info dataset movie rating: ",movie_rating_df.info())
print("info dataset director writers: ",director_writers.info())
print("info dataset actor film: ",name_df.info())

print(movie_rating_df.shape)
print(director_writers.shape)
print(name_df.shape)

# Mengubah kolom director_name dan writer_name dari string menjadi list
director_writers['director_name'] = director_writers['director_name'].apply(lambda x: x.split(','))
director_writers['writer_name'] = director_writers['writer_name'].apply(lambda x: x.split(','))

# Menampilkan 5 baris teratas
print(director_writers.head())

#Kita hanya akan membutuhkan kolom nconst, primaryName, dan knownForTitles
name_df = name_df[['nconst', 'primaryName', 'knownForTitles']]

#Tampilkan 5 baris teratas dari name_df
name_df.head()

#Melakukan pengecekan variasi
print(name_df['knownForTitles'].apply(lambda x: len(x.split(','))).unique())

#Mengubah knownForTitles menjadi list of list
name_df['knownForTitles'] = name_df['knownForTitles'].apply(lambda x: x.split(','))

#Mencetak 5 baris teratas
name_df.head()

# Menyiapkan bucket untuk dataframe hasil unnest
df_uni = []

# Melakukan unnesting kolom 'knownForTitles'
for x in ['knownForTitles']:
    # Mengulang indeks sesuai panjang list di setiap baris
    idx = name_df.index.repeat(name_df[x].str.len())

    # Membuat dataframe baru dari elemen-elemen list yang sudah dipecah
    df1 = pd.DataFrame({
        x: np.concatenate(name_df[x].values)
    })

    # Mengatur indeks df1 agar cocok dengan indeks yang diulang
    df1.index = idx

    # Menambahkan dataframe ke dalam bucket
    df_uni.append(df1)

# Menggabungkan semua dataframe menjadi satu
df_concat = pd.concat(df_uni, axis=1)

# Left join dengan dataframe awal tanpa kolom 'knownForTitles'
unnested_df = df_concat.join(name_df.drop(['knownForTitles'], axis=1), how='left')

# Mengatur urutan kolom agar sesuai dengan dataframe awal
unnested_df = unnested_df[name_df.columns.tolist()]

# Menampilkan hasil akhir
unnested_df.head()

#menyiapkan bucket untuk dataframe
df_uni = []

for col in ['primaryName']:
    #agregasi kolom PrimaryName sesuai group_col yang sudah di define di atas
    dfi = unnested_df.groupby(['knownForTitles'])[col].apply(list)
    #Lakukan append
    df_uni.append(dfi)
df_grouped = pd.concat(df_uni, axis=1).reset_index()
df_grouped.columns = ['knownForTitles','cast_name']
df_grouped.head(10)

#join antara movie table dan cast table
base_df = pd.merge(df_grouped, movie_rating_df, left_on='knownForTitles', right_on='tconst', how='inner')

#join antara base_df dengan director_writer table
base_df = pd.merge(base_df, director_writers, left_on='tconst', right_on='tconst', how='left')
base_df.head()

"""#Cleaning Data"""

base_drop = base_df.drop(['knownForTitles'], axis=1)
print(base_drop.info())
base_drop['genres'] = base_drop['genres'].fillna('Unknown')
print(base_drop.isnull().sum())
base_drop[['director_name','writer_name']] = base_drop[['director_name','writer_name']].fillna('unknown')
base_drop['genres'] = base_drop['genres'].apply(lambda x: x.split(','))

base_drop2 = base_drop.drop(['tconst','isAdult','endYear','originalTitle'], axis=1)
base_drop2 = base_drop2[['primaryTitle','titleType','startYear','runtimeMinutes','genres','averageRating','numVotes','cast_name','director_name','writer_name']]
base_drop2.columns = ['title','type','start','duration','genres','rating','votes','cast_name','director_name','writer_name']
base_drop2.head()

feature_df = base_drop2[['title','cast_name','genres','director_name','writer_name']]
feature_df.head()

def sanitize(x):
    try:
        if isinstance(x, list):
            return [i.replace(' ','').lower() for i in x]
        else:
            return [x.replace(' ','').lower()]
    except:
        print(x)
feature_cols = ['cast_name','genres','writer_name','director_name']

for col in feature_cols:
    feature_df[col] = feature_df[col].apply(sanitize)

def soup_feature(x):
    return ' '.join(x['cast_name']) + ' ' + ' '.join(x['genres']) + ' ' + ' '.join(x['director_name']) + ' ' + ' '.join(x['writer_name'])

#membuat soup menjadi 1 kolom sendiri
feature_df['soup'] = feature_df.apply(soup_feature, axis=1)

from sklearn.feature_extraction.text import CountVectorizer

#definisikan CountVectorizer dan mengubah soup tadi menjadi bentuk vector
count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(feature_df['soup'])

print(count)
print(count_matrix.shape)

from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(count_matrix, count_matrix)
print(cosine_sim)

indices = pd.Series(feature_df.index, index=feature_df['title']).drop_duplicates()

def content_recommender(title):
    #mendapatkan index dari judul film yang disebutkan
    idx = indices[title]

    #menjadikan list dari array similarity cosine sim tadi
    #hint: cosine_sim[idx]
    sim_scores = list(enumerate(cosine_sim[idx]))

    #mengurutkan film dari similarity tertinggi ke terendah
    #hint: sorted(iter, key, reverse)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    #untuk mendapatkan list judul dari item kedua sampe ke 11 (abaikan yang pertama karena yang pertama pasti judul film itu sendiri)
    sim_scores = sim_scores[1:11]

    #mendapatkan index dari judul-judul yang muncul di sim_scores
    movie_indices = [i[0] for i in sim_scores]

    #dengan menggunakan iloc, kita bisa panggil balik berdasarkan index dari movie_indices
    return base_df.iloc[movie_indices]

print(content_recommender('The Lion King'))